### PR TITLE
Some proposed changes

### PR DESCRIPTION
**Pull request by ckolos**
I chatted with @smacleod  about these yesterday. The idea behind these is to use the phabext docker images as the deploy-able artifact for production. We will need to update the circle.yml to adopt the following flow:

- Build phabext from Dockerfile using mozilla/mozphab as the base image
- Build a test image from Dockerfile-test, using the above image. This docker image will run functional tests to verify the prod image has been build properly
- Deploy only from phabext to prod
- ideally, we would pin the prod Dockerfile with a distinct SHA for the source docker image (vs. :latest)

Thoughts?

production Dockerfile changes

  - Use mozilla/mozphab as base image
  - export /app from here since this is the default image
  - remove blank lines

create "test" Dockerfile

  - use production image that will have just been built in circle as the base image
  - use build script to install pieces required for testing

create build_test.sh script

  - installs test requirements and required text files 'outside' of Dockerfile

### CODE REVIEW

**Comment by darkwing** [comment]
Works for me

**Comment by zalun** [comment]
I like the idea

**Comment by zalun** [comment]
As we said at the standup "let's discuss here"...
I like it as phabext wasn't doing anything except of sharing the volume with mozphab.
I think we should also add run_test.sh which will do arc liberate and arc unit on extensions __tests__ folders, but it might be done in a separate PR.

**Comment by zalun** [comment]
As we said at the standup "let's discuss here"...
I like it as phabext wasn't doing anything except of sharing the volume with mozphab.
I think we should also add run_test.sh which will do arc liberate and arc unit on extensions __tests__ folders, but it might be done in a separate PR.

**Comment by smacleod** [comment]
> I think we should also add run_test.sh which will do arc liberate and arc unit on extensions tests folders
@zalun arc liberate should only be run when there is a change in the classes the extension provides, and the resulting files should be committed to the repository. It's not something we should be running at build time.

**Comment by zalun** [comment]
@smacleod  __phutil files should be then pushed to the phabext container and copied to /app/phabricator/src

**Comment by dklawren** [comment]
I think the only issue I have, which is minor, is naming. Also the fact that we would then be deploying from a non-mozilla-services organization. It is confusing to me that we are deploying 'phabricator-extensions' to prod and not 'mozphab'. What if we renamed the repos?:

'mozilla-services/mozphab' -> 'mozilla-services/moz-phab-base'
'mozilla-conduit/phabricator-extensions' -> 'mozilla-conduit/moz-phab-deploy'

or something else along those lines.

Thoughts?
dkl

**Comment by zalun** [comment]
I've been checking the build and the files created in ```build_test.sh``` are not present in the container's ```/app``` directory.
BTW the ```.arcunit``` and ```.arcconfig``` from ```/app/phabricator``` are perfectly and would work if only ```arc``` would like to read them.

**Comment by ckolos** [comment]
moving these changes to a different branch and closing this one.

**Pull request closed without merging**
